"""
SQLAlchemy ORM models for the Multi-Agent Research System.
Defines Chat, Document, and Report database tables.
"""

from sqlalchemy import (
    Column,
    Integer,
    String,
    Text,
    DateTime,
    ForeignKey,
    JSON,
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from database.connection import Base


class Chat(Base):
    """
    Represents a research chat session.
    Stores the user query, the agent response, and the step-by-step agent execution log.
    """

    __tablename__ = "chats"

    id = Column(Integer, primary_key=True, index=True)
    query = Column(Text, nullable=False)
    response = Column(Text, nullable=True)
    agent_steps = Column(JSON, nullable=True)  # List of dicts describing each agent step
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationship: one chat can produce one report
    report = relationship("Report", back_populates="chat", uselist=False)

    def __repr__(self) -> str:
        return f"<Chat id={self.id} query='{self.query[:50]}...'>"


class Document(Base):
    """
    Represents an uploaded or indexed document.
    Stores metadata about the source file and its ChromaDB embedding reference.
    """

    __tablename__ = "documents"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String(500), nullable=False)
    source = Column(String(1000), nullable=True)  # URL or file name
    file_path = Column(String(1000), nullable=True)  # Local path to the stored file
    embedding_id = Column(String(500), nullable=True)  # ChromaDB collection IDs prefix
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    def __repr__(self) -> str:
        return f"<Document id={self.id} title='{self.title}'>"


class Report(Base):
    """
    Represents a structured research report generated by the agent pipeline.
    Links back to the originating Chat session.
    """

    __tablename__ = "reports"

    id = Column(Integer, primary_key=True, index=True)
    chat_id = Column(Integer, ForeignKey("chats.id"), nullable=True)
    title = Column(String(1000), nullable=False)
    executive_summary = Column(Text, nullable=True)
    findings = Column(JSON, nullable=True)   # List of finding strings
    references = Column(JSON, nullable=True)  # List of {title, url, source} dicts
    conclusion = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationship back to the chat
    chat = relationship("Chat", back_populates="report")

    def __repr__(self) -> str:
        return f"<Report id={self.id} title='{self.title}'>"
